name: system_monitor_controller
description: "A plugin package to gather information about the operating system"
version: 0.0.1
homepage: https://github.com/LuizJarduli/system_monitor_controller

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  system_monitor_controller_platform_interface:
    # FIXME(lugalokinho): change to published package when its done
    path: ../system_monitor_controller_platform_interface
  system_monitor_controller_android:
    # FIXME(lugalokinho): change to published package when its done
    path: ../system_monitor_controller_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: com.lugalokinho.system_monitor_controller_android
      ios:
        pluginClass: SystemMonitorControllerPlugin
